modLoader = "javafml"
loaderVersion = "[4,)"
license = "LGPL-3.0-only"

issueTrackerURL = "https://github.com/Shihyeon/ImagictHud/issues"

[[mods]]
modId = "imagicthud"

displayName = "ImagictHud"

version = "${version}"

logoFile = "assets/imagicthud/icon.png"

authors = "Shihyeon"

description = '''
Displays the player's head, nickname, coordinates, indicators, etc. on the in-game HUD.
'''

modUrl = "https://modrinth.com/mod/imagict-hud"
displayURL = "https://modrinth.com/mod/imagict-hud"

[[mixins]]
config = "imagicthud.mixins.json"

[[mixins]]
config = "imagicthud.neoforge.mixins.json"

[[accessTransformers]]
file = "META-INF/accesstransformer.cfg"

[[dependencies.imagicthud]]
modId = "neoforge"
type = "required" #mandatory (Can be one of "required", "optional", "incompatible" or "discouraged")
versionRange = "[${neoforge_version},)"
ordering = "NONE" # The order that this dependency should load in relation to your mod, required to be either 'BEFORE' or 'AFTER' if the dependency is not mandatory
side = "CLIENT" # Side this dependency is applied on - 'BOTH', 'CLIENT' or 'SERVER'

[[dependencies.imagicthud]]
modId = "minecraft"
type = "required"
versionRange = "[${minecraft_version},)"
ordering = "NONE"
side = "CLIENT"