# This workflow will build a Java project with Brachyra
# For more information see: docs/development/brachyura.md

name: build-release

on:
  release:
    types:
      - published

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Java 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21

      - name: Make gradle wrapper executable
        run: chmod +x ./gradlew

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3
        with:
          cache-read-only: false

      - name: Run build with Gradle Wrapper
        run: ./gradlew build remapJar -Dbuild.release=true

      # https://github.com/Kir-Antipov/mc-publish
      - name: Upload artifacts to Modrinth and GitHub
        uses: Kir-Antipov/mc-publish@v3.3
        with:
          modrinth-id: uWeqs5CX
          modrinth-token: ${{ secrets.MODRINTH_TOKEN }}

          github-token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}

          files: build/libs/!(*-@(dev|sources|all)).jar

          version-type: release
          loaders: fabric
          dependencies: |
            fabric-api{modrinth:P7dR8mSH}
            yacl{modrinth:1eAoo2KR}
            modmenu(optional){modrinth:mOgUt4GM}